#ifndef POLY_CONFIG_HPP
#define POLY_CONFIG_HPP

#ifdef POLY_MACROS
#define POLY_USE_MACROS 1
#else
#define POLY_USE_MACROS 0
#endif

#ifdef POLY_INJECT
#define POLY_USE_INJECTOR 1
#else
#define POLY_USE_INJECTOR 0
#endif

#ifdef POLY_INJECT_METHODS
#define POLY_USE_METHOD_INJECTOR 1
#else
#define POLY_USE_METHOD_INJECTOR 0
#endif

#ifdef POLY_INJECT_PROPERTIES
#define POLY_USE_PROPERTY_INJECTOR 1
#else
#define POLY_USE_PROPERTY_INJECTOR 0
#endif

#ifdef POLY_DEFAULT_PROPERTY_ACCESS
#define POLY_USE_DEFAULT_PROPERTY_ACCESS 1
#else
#define POLY_USE_DEFAULT_PROPERTY_ACCESS 0
#endif

#ifdef POLY_DEFAULT_EXTEND
#define POLY_USE_DEFAULT_EXTEND 1
#else
#define POLY_USE_DEFAULT_EXTEND 0
#endif

#endif
